// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwmQ7VKF6LUo6G3MLgqRWCCjyZL4p57hw',
    appId: '1:332912225304:web:e31b10d9ac3b8915e1676d',
    messagingSenderId: '332912225304',
    projectId: 'todo-app-a9f91',
    authDomain: 'todo-app-a9f91.firebaseapp.com',
    storageBucket: 'todo-app-a9f91.appspot.com',
    measurementId: 'G-Z946D0WT0R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4NgnqY1gXseVxl1eZs9YhbZmLK-FGGPo',
    appId: '1:332912225304:android:b426b8c9f0ace622e1676d',
    messagingSenderId: '332912225304',
    projectId: 'todo-app-a9f91',
    storageBucket: 'todo-app-a9f91.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDo6DsVnxXU-CYqQoyNzZI94ZNtnpYXfzw',
    appId: '1:332912225304:ios:f87cc2dabdf14374e1676d',
    messagingSenderId: '332912225304',
    projectId: 'todo-app-a9f91',
    storageBucket: 'todo-app-a9f91.appspot.com',
    iosBundleId: 'com.example.flutterTodoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDo6DsVnxXU-CYqQoyNzZI94ZNtnpYXfzw',
    appId: '1:332912225304:ios:6d79b74162dab267e1676d',
    messagingSenderId: '332912225304',
    projectId: 'todo-app-a9f91',
    storageBucket: 'todo-app-a9f91.appspot.com',
    iosBundleId: 'com.example.flutterTodoApp.RunnerTests',
  );
}
